# Cargo.toml
[package]
name = "rustdb"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.8"
serde = { version = "1.0", features = ["derive"] }
nom = "7.0"
bincode = "1.0"
tokio = { version = "1.0", features = ["full"] }
memmap2 = "0.9.5"
parking_lot = "0.12"